export default [
  {
    "_id": "Q101",
    "title": "HTML Basics Quiz",
    "course": "RS101",
    "available": "2025-06-10T00:00:00", // Example: Available from June 10, 2025
    "until": "2025-06-25T23:59:59",    // Example: Available until June 25, 2025
    "due": "2025-06-26T23:59:00",
    "description": "A quiz covering fundamental concepts in HTML.",
    "points": 100,
    "numQuestions": 10,
    "published": true,
    "quizType": "Graded Quiz",
    "assignmentGroup": "Quizzes",
    "shuffleAnswers": true,
    "timeLimit": 20, // in minutes
    "multipleAttempts": false,
    "howManyAttempts": 1,
    "showCorrectAnswers": "After Due Date",
    "accessCode": "",
    "oneQuestionAtATime": true,
    "webcamRequired": false,
    "lockQuestionsAfterAnswering": false
  },
  {
    "_id": "Q102",
    "title": "CSS Styling Quiz",
    "course": "RS101",
    "available": "2025-05-13T00:00:00", // Example: Available from May 13, 2025 (past)
    "until": "2025-06-10T23:59:59",    // Example: Closed as of June 10, 2025
    "due": "2025-06-11T23:59:00",
    "description": "Test your knowledge of CSS properties and selectors.",
    "points": 120,
    "numQuestions": 15,
    "published": false,
    "quizType": "Practice Quiz",
    "assignmentGroup": "Quizzes",
    "shuffleAnswers": true,
    "timeLimit": 30,
    "multipleAttempts": true,
    "howManyAttempts": 3,
    "showCorrectAnswers": "Always",
    "accessCode": "CSS2025",
    "oneQuestionAtATime": false,
    "webcamRequired": false,
    "lockQuestionsAfterAnswering": false
  },
  {
    "_id": "Q103",
    "title": "JavaScript Fundamentals",
    "course": "RS101",
    "available": "2025-06-20T00:00:00", // Example: Available in the future
    "until": "2025-07-05T23:59:59",
    "due": "2025-07-15T23:59:00",
    "description": "An exam covering basic JavaScript concepts and syntax.",
    "points": 150,
    "numQuestions": 20,
    "published": true,
    "quizType": "Graded Quiz",
    "assignmentGroup": "Exams",
    "shuffleAnswers": false,
    "timeLimit": 60,
    "multipleAttempts": false,
    "howManyAttempts": 1,
    "showCorrectAnswers": "Never",
    "accessCode": "JSFUNDAMENTALS",
    "oneQuestionAtATime": true,
    "webcamRequired": true,
    "lockQuestionsAfterAnswering": true
  },
  {
    "_id": "Q201",
    "title": "Aerodynamics Principles Quiz",
    "course": "RS102",
    "available": "2024-05-27T00:00:00", // Past date, but until date might make it closed
    "until": "2024-06-10T23:59:59", // Past date, making it closed
    "due": "2024-06-20T23:59:00",
    "description": "A quiz covering fundamental concepts in aerodynamics.",
    "points": 80,
    "numQuestions": 8,
    "published": true,
    "quizType": "Practice Quiz",
    "assignmentGroup": "Quizzes",
    "shuffleAnswers": true,
    "timeLimit": 15,
    "multipleAttempts": true,
    "howManyAttempts": 5,
    "showCorrectAnswers": "Immediately",
    "accessCode": "",
    "oneQuestionAtATime": false,
    "webcamRequired": false,
    "lockQuestionsAfterAnswering": false
  },
  {
    "_id": "Q202",
    "title": "Fluid Dynamics Quiz",
    "course": "RS102",
    "available": "2025-06-06T00:00:00", // Currently available
    "until": "2025-06-28T23:59:59",
    "due": "2025-06-30T23:59:00",
    "description": "Analyze the flow of air over an aircraft wing.",
    "points": 100,
    "numQuestions": 12,
    "published": true,
    "quizType": "Graded Survey",
    "assignmentGroup": "Quizzes",
    "shuffleAnswers": false,
    "timeLimit": null, // No time limit for survey
    "multipleAttempts": false, // Surveys are usually single attempt
    "howManyAttempts": 1,
    "showCorrectAnswers": "Never",
    "accessCode": "",
    "oneQuestionAtATime": true,
    "webcamRequired": false,
    "lockQuestionsAfterAnswering": false
  },
  {
    "_id": "Q203",
    "title": "Thermal Analysis Quiz",
    "course": "RS102",
    "available": "2025-06-16T00:00:00", // Currently available
    "until": "2025-06-22T23:59:59",
    "due": "2025-06-23T23:59:00",
    "description": "Analyze the thermal properties and heating of materials.",
    "points": 110,
    "numQuestions": 10,
    "published": false, // This will be hidden from students by default
    "quizType": "Ungraded Survey",
    "assignmentGroup": "Quizzes",
    "shuffleAnswers": true,
    "timeLimit": null,
    "multipleAttempts": false,
    "howManyAttempts": 1,
    "showCorrectAnswers": "Never",
    "accessCode": "",
    "oneQuestionAtATime": false,
    "webcamRequired": false,
    "lockQuestionsAfterAnswering": false
  },
  {
    "_id": "Q301",
    "title": "Structural Design Quiz",
    "course": "RS103",
    "available": "2025-05-06T00:00:00", // Past due, Closed (Past Due)
    "until": "2025-05-12T23:59:59",
    "due": "2025-05-13T23:59:00",
    "description": "Design the structural components for a spacecraft.",
    "points": 130,
    "numQuestions": 18,
    "published": true,
    "quizType": "Graded Quiz",
    "assignmentGroup": "Projects",
    "shuffleAnswers": true,
    "timeLimit": 45,
    "multipleAttempts": true,
    "howManyAttempts": 2,
    "showCorrectAnswers": "After Last Attempt",
    "accessCode": "STRUCTENG",
    "oneQuestionAtATime": true,
    "webcamRequired": false,
    "lockQuestionsAfterAnswering": false
  },
  {
    "_id": "Q302",
    "title": "Orbital Mechanics Quiz",
    "course": "RS103",
    "available": "2025-06-16T00:00:00", // Available now
    "until": "2025-06-22T23:59:59",
    "due": "2025-06-23T23:59:00",
    "description": "Calculate the orbital parameters of a spacecraft.",
    "points": 140,
    "numQuestions": 14,
    "published": false, // This will be hidden from students by default
    "quizType": "Practice Quiz",
    "assignmentGroup": "Exams",
    "shuffleAnswers": false,
    "timeLimit": 60,
    "multipleAttempts": false,
    "howManyAttempts": 1,
    "showCorrectAnswers": "Never",
    "accessCode": "",
    "oneQuestionAtATime": true,
    "webcamRequired": true,
    "lockQuestionsAfterAnswering": false
  },
  {
    "_id": "Q303",
    "title": "Systems Engineering Quiz",
    "course": "RS103",
    "available": "2025-05-07T00:00:00", 
    "until": "2025-05-13T23:59:59",
    "due": "2025-05-14T23:59:00",
    "description": "An exam covering systems engineering principles.",
    "points": 150,
    "numQuestions": 25,
    "published": true,
    "quizType": "Graded Quiz",
    "assignmentGroup": "Assignments",
    "shuffleAnswers": true,
    "timeLimit": 75,
    "multipleAttempts": false,
    "howManyAttempts": 1,
    "showCorrectAnswers": "After Grade Posted",
    "accessCode": "SYSENG25",
    "oneQuestionAtATime": false,
    "webcamRequired": false,
    "lockQuestionsAfterAnswering": false
  }
];